config/routes.rb
FlagApp::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :users do 
    collection { post :sort }
    resources :images
    resources :journals
    resources :scrapbooks
  end 

  match 'signup', to: "users#new"
  match 'login', to: "sessions#new"
  match 'logout', to: "sessions#destroy"
  match 'profile', to: "users#show"
  match 'about', to: "static_pages#about"
  match 'dashboard', to: "static_pages#dashboard"
  match 'book', to: "static_pages#book"
  match 'users/:id/scrapbook/day', as:'day', to: "scrapbooks#day"
  match 'users/:id/scrapbook/week', as:'week', to: "scrapbooks#week"
  match 'users/:id/scrapbook/month', as:'month', to: "scrapbooks#month"
  match 'users/:id/scrapbook/year', as:'year', to: "scrapbooks#year"
  match 'weekly_scrapbook', to: "static_pages#weekly"
  match 'monthly_scrapbook', to: "static_pages#monthly"
  match 'yearly_scrapbook', to: "static_pages#yearly"
  match "users/:id/images/:id/resize", to: "images#resize"
  match "users/:id/images/:id/time_frame", to: "images#time_frame"
  match "users/:id/images/:id/z_index", to: "images#z_index"
  match "users/:id/images/:id/drag", to: "images#drag"
  match "users/:id/images/:id/update", to: "images#update"
  match "users/:id/images/:id/edit", to: "images#edit"
  match "users/:id/update", to: "users#update"
  match "users/:id/update_reg_coor", to: "users#update_reg_coor"
  match "users/create", to: "users#create", as: "create_guest"
  match "member_index", to: "users#member_index"
  match "users/:id/regional_coor", to: "users#regional_coor"
  match "static_pages/intro_movie", to: "static_pages#intro_movie", as: "intro_movie"
  
  match "announcement_partial", :to => "announcements#announcement_partial"
  
  match "event_partial", :to => "events#event_partial"
  match "image_partial", :to => "images#image_partial"
  match "coordinators", :to => "users#coordinators"

  resources :users do 
    collection { post :sort }
  	resources :images
    resources :journals
    resources :scrapbooks
  end 
  resources :partials
  resources :messages

  # announcements
  match 'announcements/:id/hide', as: 'hide_announcement', to: 'announcements#hide'
  resources :announcements do
    collection { post :sort }
  end
  match "announcements/:id/announcement_status", to: "announcements#announcement_status", as: "announcement_status"
  match "announcements/:id/announcement_starts_at", to: "announcements#announcement_starts_at", as: "announcement_starts_at"
  match "announcements/:id/announcement_ends_at", to: "announcements#announcement_ends_at", as: "announcement_ends_at"
 
   
  # page
  resources :pages do
    collection { post :sort }
    member { put :link, :status }
  end
  # match 'pages/:id/status', to: 'pages#status', as: 'status'
  
  # announcements
  resources :announcements do 
    resources :statuses_statusables
  end
  
  # events
  resources :events do
    collection { post :sort }
  end
  match 'events/:id/event_status', to: 'events#event_status', as: 'event_status'
  match "events/:id/event_starts_at", to: "events#event_starts_at", as: "event_starts_at"
  match "events/:id/event_ends_at", to: "events#event_ends_at", as: "event_ends_at"

  resources :password_resets
  resources :votes
  resources :links
  resources :sessions
  resources :roles
  resources :programs
  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"
  

  root :to => "pages#show", :id => 'home'

 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController 
  before_filter :current_user, :except => [:home]

  layout 'dashboard'
  
  include ApplicationHelper

  

  def profile
    @page = page_requested
    redirect_to create_guest_path(page: @page) unless current_user
  	@user = @current_user
  end

  def about
    @page = page_requested
    redirect_to create_guest_path(page: @page) unless current_user
  	@user = @current_user
  end

  def book
    @page = page_requested
    redirect_to create_guest_path(page: @page) unless current_user
    @user = @current_user
  end

  def dashboard
    @pages = Page.all
    static_array = %w[Partial Profile Role Supermodel]
    @active_models = Supermodel.where("visible = true AND name NOT IN (?)", static_array).order("name ASC")
    @static_models = Supermodel.where("visible = true AND name IN (?)", static_array).order("name ASC")
  end

  def intro_movie
    respond_to do |format|
      format.js
    end
  end

end

app/views/static_pages/_intro_movie.html.erb
<div id="movie_container">
	<%= render("shared/close") %>
	<iframe width="640" height="480" src="http://www.youtube.com/embed/5aU97TvFPHM" frameborder="0" allowfullscreen></iframe>
</div>

app/views/static_pages/_table_list.html.erb
<% models_list.each do |visible| %> 
	<% count = visible.name.constantize.all.count %>
	<% model_name = visible.name.downcase %>
		<%= content_tag :li, link_to("#{visible.name}s (#{count})", send("#{model_name}s_path")) %>

<% end %>
<%= content_tag :li, link_to("Supermodel", supermodels_path) if current_user.role? :SuperAdmin %>

app/views/static_pages/about.html.erb
<h1>Our Vision</h1>

<p>To promote global understanding and world peace by providing families and youngsters from across the globe with the best intercultural experience friendship can buy.</p>

<h2>Overseas Representation</h2>

<p>FLAG is represented internationally by authorized agents who are responsible for promoting the FLAG program overseas, for the recruitment and pre-departure orientation of all program participants, and for providing assistance to the natural parents of the program participants during their exchange experience.</p>

<h2>U.S Representation</h2>

<p>In the U.S., FLAG is locally represented in a number of states by a network of authorized Field Coordinators. Our Field FilteredCoordinators (mostly former FLAG host families) are reliable and experienced individuals who are trained to screen, recruit and personally interview U.S. host families and outbound American exchange students. They are also responsible for providing local assistance to FLAG's inbound students,U.S. host families, and high schools during their intercultural experience.</p>


<h2>Statistics</h2>

	<ul>Countries Served: 	
		<li>28</li>
	</ul>

<ul>Participants: 	
		<li>2011/2012: 212 J1 students</li>
		<li>Beyond F1: Participants limited to 100 per year.</li>
		<li>English Immersion & Global Leadership Camps: 200+, space permitting, per site.</li>
</ul>

<h2>Credentials</h2>

	<ul>
	    <li>Not-for-Profit Tax Exempt Organization</li>
	    <li>Established in 1989</li>
	    <li>Granted Official Sponsor Designation by the U.S. Dept. of State in 1990</li>
	    <li>Accepted for Listing in C.S.I.E.T.'s 2012-13 Advisory List</li>
	</ul>

app/views/static_pages/book.html.erb
<div id="home_content">
	<%= image_tag "homepage.png", style:"margin:-93px 0px 0px -110px" %>
	
	<%= link_to content_tag(:div, "", class: "sign_in_from_home_page"), new_user_path, remote: true %>
	<div class="sign_up_form_container"></div>
	
	
</div>

app/views/static_pages/dashboard.html.erb
<% update_list %> 
<div class="dash_main">

	<div class="l_col">
		<div class="dash_nav">

			<%= content_tag :h3, "Dynamic Tables", class: "dynamic_tables super_tables" %>
			<ul class= "dynamic_tables_list">
				<%= render 'static_pages/table_list', :models_list => @active_models %>
			</ul>

			<%= content_tag :h3, "Static Tables", class: "static_tables super_tables" %>
			<ul class= "static_tables_list hidden">
				<%= render 'static_pages/table_list', :models_list => @static_models %>
			</ul>
			
		</div>
	</div>

		<div class="m_col">
			<h2>Welcome to your dashboard!</h2>
			<p>We've customized this dashboard for you, and it will be the hub that helps you manage your web application.</p>
		</div>

		<div class="r_col">

			<div class="news">
				<h3>News</h3>
				<p>We don't have anything new to share right now, but from time to time this area of the dashboard contains marketing tips, new websites, and other stuff that we think our clients might find helpful or interesting.</p>
			</div>

		</div>
</div>

app/views/static_pages/home.html.erb
<div id="home_content">
	<h1>Welcome to FLAG!</h1>

	<p><%= image_tag "students.png", size:"600x670", class:"right students" %> FLAG is a Michigan based non-profit organization that promotes and supports global understanding through international educational travel. Our programs are designed to develop personal growth, interpersonal communication skills, intercultural awareness, and academic advancement.
	</p>

	<h2>About the Grants Program</h2>
	<p>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur aliquam dolorem odio repudiandae corporis nostrum dicta illum fugiat dolor pariatur porro architecto quas quidem. Quaerat quibusdam ullam numquam facilis animi et hic atque magnam omnis nihil expedita modi id? Molestiae delectus quaerat laboriosam voluptate doloremque reprehenderit saepe ab et velit libero asperiores eum ducimus repudiandae minus nemo adipisci error odio quas unde non magni fuga autem repellendus neque obcaecati vero nesciunt earum? Quod recusandae neque voluptatum nulla ratione. Illo repudiandae recusandae cupiditate sit magnam molestiae ipsam delectus doloribus quibusdam ab rem consequatur eos cum laudantium architecto sequi corrupti ad debitis sed esse itaque corporis dicta placeat a nam autem quae illum facere alias quisquam atque necessitatibus nemo quidem error reprehenderit dolorum explicabo ratione praesentium eaque aliquid. Ipsam harum excepturi distinctio velit molestiae assumenda minima vero placeat porro consequuntur dolore obcaecati ratione quod! Ab possimus odio voluptatem beatae quod quaerat earum commodi temporibus dignissimos cumque? A suscipit qui eum repudiandae fugit porro dolores velit. Reprehenderit tempore debitis enim voluptates obcaecati quisquam incidunt autem delectus exercitationem placeat eius unde aliquam et voluptatibus perspiciatis consequatur nesciunt vero magni minima aperiam pariatur voluptatem rem magnam voluptatum corporis tempora consectetur neque eum repellendus error assumenda.
	</p>
	
	

</div>

app/views/static_pages/intro_movie.js.erb
$("#lightbox").remove()
$("body").append("<div id='lightbox'></div>")
$("#lightbox").append("<%= j render 'static_pages/intro_movie' %>")

app/views/static_pages/profile.html.erb
<%= render 'shared/announcements' %>

app/views/static_pages/scrap.html.erb
<div id="home_content">
	<%= image_tag "homepage.png" %>
	
	<%= link_to content_tag(:div, "", class: "sign_in_from_home_page"), new_user_path, remote: true %>
	<div class="sign_up_form_container"></div>
	
	
</div>