config/routes.rb
FlagApp::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :users do 
    collection { post :sort }
    resources :images
    resources :journals
    resources :scrapbooks
  end 

  match 'signup', to: "users#new"
  match 'login', to: "sessions#new"
  match 'logout', to: "sessions#destroy"
  match 'profile', to: "users#show"
  match 'about', to: "static_pages#about"
  match 'dashboard', to: "static_pages#dashboard"
  match 'book', to: "static_pages#book"
  match 'users/:id/scrapbook/day', as:'day', to: "scrapbooks#day"
  match 'users/:id/scrapbook/week', as:'week', to: "scrapbooks#week"
  match 'users/:id/scrapbook/month', as:'month', to: "scrapbooks#month"
  match 'users/:id/scrapbook/year', as:'year', to: "scrapbooks#year"
  match 'weekly_scrapbook', to: "static_pages#weekly"
  match 'monthly_scrapbook', to: "static_pages#monthly"
  match 'yearly_scrapbook', to: "static_pages#yearly"
  match "users/:id/images/:id/resize", to: "images#resize"
  match "users/:id/images/:id/time_frame", to: "images#time_frame"
  match "users/:id/images/:id/z_index", to: "images#z_index"
  match "users/:id/images/:id/drag", to: "images#drag"
  match "users/:id/images/:id/update", to: "images#update"
  match "users/:id/images/:id/edit", to: "images#edit"
  match "users/:id/update", to: "users#update"
  match "users/:id/update_reg_coor", to: "users#update_reg_coor"
  match "users/create", to: "users#create", as: "create_guest"
  match "member_index", to: "users#member_index"
  match "users/:id/regional_coor", to: "users#regional_coor"
  match "static_pages/intro_movie", to: "static_pages#intro_movie", as: "intro_movie"
  
  match "announcement_partial", :to => "announcements#announcement_partial"
  
  match "event_partial", :to => "events#event_partial"
  match "image_partial", :to => "images#image_partial"
  match "coordinators", :to => "users#coordinators"

  resources :users do 
    collection { post :sort }
  	resources :images
    resources :journals
    resources :scrapbooks
  end 
  resources :partials
  resources :messages

  # announcements
  match 'announcements/:id/hide', as: 'hide_announcement', to: 'announcements#hide'
  resources :announcements do
    collection { post :sort }
  end
  match "announcements/:id/announcement_status", to: "announcements#announcement_status", as: "announcement_status"
  match "announcements/:id/announcement_starts_at", to: "announcements#announcement_starts_at", as: "announcement_starts_at"
  match "announcements/:id/announcement_ends_at", to: "announcements#announcement_ends_at", as: "announcement_ends_at"
 
   
  # page
  resources :pages do
    collection { post :sort }
    member { put :link, :status }
  end
  # match 'pages/:id/status', to: 'pages#status', as: 'status'
  
  # announcements
  resources :announcements do 
    resources :statuses_statusables
  end
  
  # events
  resources :events do
    collection { post :sort }
  end
  match 'events/:id/event_status', to: 'events#event_status', as: 'event_status'
  match "events/:id/event_starts_at", to: "events#event_starts_at", as: "event_starts_at"
  match "events/:id/event_ends_at", to: "events#event_ends_at", as: "event_ends_at"

  resources :password_resets
  resources :votes
  resources :links
  resources :sessions
  resources :roles
  resources :programs
  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"
  

  root :to => "pages#show", :id => 'home'

 
end

app/models/supermodel.rb
class Supermodel < ActiveRecord::Base
	attr_accessible :name, :visible


	def self.visible
		where(visible: true)
	end

	def self.hidden
		where("visible = (?)",false)
	end

end

app/controllers/supermodels_controller.rb
class SupermodelsController < ApplicationController
 	authorize_resource
	layout 'dashboard'
	before_filter :authorize
	def new 
		@supermodel = Supermodel.new
	end

	def index 
		all_supermodel_states
	end

	def show
		find_supermodel
	end

	def create
		@supermodel = Supermodel.find(params[:supermodel])
		respond_to do |format|
			if @supermodel.save
				format.html { redirect_to dashboard_path, "model saved" }
				format.js
			else
				format.html { render 'new', notice: "model not saved" }
				format.js
			end
		end
	end

	def edit
		find_supermodel 

	end

	def update
		find_supermodel
		authorize! :update, @supermodel
		all_supermodel_states
		respond_to do |format|
	      if @supermodel.update_attributes(params[:supermodel])
	        format.html { redirect_to dashboard_path, notice: 'model was successfully updated.' }
	        format.js
	      else
	        format.html { render action: "edit" }
	        format.js { render json: @supermodel.errors, status: :unprocessable_entity }
	      end
	    end

	end


	def find_supermodel
		@supermodel = Supermodel.find(params[:id])
	end

	def sort
		all_supermodel_states
		params[:supermodel].each_with_index do |id, index|
			Supermodel.update_all({ position: index+1}, {id: id })
		end
		render 'update.js'

	end

	def model_status
		find_supermodel
		all_supermodel_states
		visible = params[:supermodel][:visible]
		@supermodel.update_attributes({visible: visible})
		Supermodel.visible.each_with_index do |id, index|
			Supermodel.update_all({position: index+1}, {id: id})
		end
		render 'update.js'

	end

	def all_supermodel_states
		@visible_supermodels = Supermodel.visible.order("name ASC")
		@hidden_supermodels = Supermodel.hidden.order("name ASC")
	end

end

app/views/supermodels/_form.html.erb
 <%= form_for(@supermodel) do |f| %>
    <%= render 'shared/errors', object: @supermodel %>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name,:readonly => true %>
    </div>

     <div class="field">
      <%= f.label :visible %><br />
      <%= f.check_box :visible %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/supermodels/_supermodel.html.erb
<%= content_tag_for :li, supermodel do %>
	<ul class="instance_detail">
		<%= content_tag :li, supermodel.name, class:"title"  %>
		<%= form_for supermodel, class: "supermodel_ajax_edit", :url => {controller:  "supermodels", action: "model_status", id: supermodel.id }, remote: true do |a| %>
			<%= a.check_box :visible, class: "supermodels_status_checkbox", id: "supermodel#{supermodel.id}" %>
		<% end %>
		
		<ul class="crud_buttons">
			<%= content_tag :li, link_to("edit", edit_supermodel_path(supermodel)) %>
			<%= content_tag :li, link_to("view", supermodel_path(supermodel)) %>
			
		</ul>
		
	</ul>
	<br class="clear">
<% end %>

app/views/supermodels/edit.html.erb
<%= content_tag :h1, "Edit" %>

<%= render 'form' %>

app/views/supermodels/index.html.erb
<%= content_tag :h1, "Application Models" %>


<ul class="model_table supermodelStates" id="visible_supermodels" data-update-url="<%= sort_supermodels_url %>">
	<%= content_tag :h3, "Tables (#{Supermodel.visible.count})" %>
		<%= render @visible_supermodels %>
</ul>

<ul class="model_table supermodelStates" id="hidden_supermodels" data-update-url="<%= sort_supermodels_url %>">
	<%= content_tag :h3, "Hidden Tables (#{Supermodel.hidden.count})" %>
	<%= render @hidden_supermodels %>
</ul>

app/views/supermodels/update.js.erb
$("#visible_supermodels").html("<%= j render @visible_supermodels %>").prepend("<h3>Tables (<%= Supermodel.visible.count %>)</h3")
$("#hidden_supermodels").html("<%= j render @hidden_supermodels %>").prepend("<h3>Hidden Tables (<%= Supermodel.hidden.count %>)</h3")