config/routes.rb
FlagApp::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :users do 
    collection { post :sort }
    resources :images
    resources :journals
    resources :scrapbooks
  end 

  match 'signup', to: "users#new"
  match 'login', to: "sessions#new"
  match 'logout', to: "sessions#destroy"
  match 'profile', to: "users#show"
  match 'about', to: "static_pages#about"
  match 'dashboard', to: "static_pages#dashboard"
  match 'book', to: "static_pages#book"
  match 'users/:id/scrapbook/day', as:'day', to: "scrapbooks#day"
  match 'users/:id/scrapbook/week', as:'week', to: "scrapbooks#week"
  match 'users/:id/scrapbook/month', as:'month', to: "scrapbooks#month"
  match 'users/:id/scrapbook/year', as:'year', to: "scrapbooks#year"
  match 'weekly_scrapbook', to: "static_pages#weekly"
  match 'monthly_scrapbook', to: "static_pages#monthly"
  match 'yearly_scrapbook', to: "static_pages#yearly"
  match "users/:id/images/:id/resize", to: "images#resize"
  match "users/:id/images/:id/time_frame", to: "images#time_frame"
  match "users/:id/images/:id/z_index", to: "images#z_index"
  match "users/:id/images/:id/drag", to: "images#drag"
  match "users/:id/images/:id/update", to: "images#update"
  match "users/:id/images/:id/edit", to: "images#edit"
  match "users/:id/update", to: "users#update"
  match "users/:id/update_reg_coor", to: "users#update_reg_coor"
  match "users/create", to: "users#create", as: "create_guest"
  match "member_index", to: "users#member_index"
  match "users/:id/regional_coor", to: "users#regional_coor"
  match "static_pages/intro_movie", to: "static_pages#intro_movie", as: "intro_movie"
  
  match "announcement_partial", :to => "announcements#announcement_partial"
  
  match "event_partial", :to => "events#event_partial"
  match "image_partial", :to => "images#image_partial"
  match "coordinators", :to => "users#coordinators"

  resources :users do 
    collection { post :sort }
  	resources :images
    resources :journals
    resources :scrapbooks
  end 
  resources :partials
  resources :messages

  # announcements
  match 'announcements/:id/hide', as: 'hide_announcement', to: 'announcements#hide'
  resources :announcements do
    collection { post :sort }
  end
  match "announcements/:id/announcement_status", to: "announcements#announcement_status", as: "announcement_status"
  match "announcements/:id/announcement_starts_at", to: "announcements#announcement_starts_at", as: "announcement_starts_at"
  match "announcements/:id/announcement_ends_at", to: "announcements#announcement_ends_at", as: "announcement_ends_at"
 
   
  # page
  resources :pages do
    collection { post :sort }
    member { put :link, :status }
  end
  # match 'pages/:id/status', to: 'pages#status', as: 'status'
  
  # announcements
  resources :announcements do 
    resources :statuses_statusables
  end
  
  # events
  resources :events do
    collection { post :sort }
  end
  match 'events/:id/event_status', to: 'events#event_status', as: 'event_status'
  match "events/:id/event_starts_at", to: "events#event_starts_at", as: "event_starts_at"
  match "events/:id/event_ends_at", to: "events#event_ends_at", as: "event_ends_at"

  resources :password_resets
  resources :votes
  resources :links
  resources :sessions
  resources :roles
  resources :programs
  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"
  

  root :to => "pages#show", :id => 'home'

 
end

app/models/program.rb
class Program < ActiveRecord::Base
	attr_accessible :name, :body

	has_many :user_programs
	has_many :users, :through => :user_programs
	
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController 
	layout 'dashboard'
	authorize_resource
	def new 
		@program = Program.new	
	end

	def index
		@programs = Program.all 
	end

	def show 
		find_program
	end

	def edit 
		find_program
	end

	def create 
		@program = Program.new(params[:program])
		respond_to do |format|
			if @program.save
				format.html { redirect_to @program, :notice => "The #{@program.name} program was successfully created" }
				format.js
			else
				format.html { redirect_to "new", :notice => "program could not be created. Please fill out all ** fields"}
			end
		end
	end

	def update
		find_program
		respond_to do |format|
			if @program.update_attributes(params[:program])
				format.html { redirect_to @program, :notice => "The #{@program.name} program was succesfully updated"}
				format.js
			else
				format.html { render :action => "edit"}
			end
		end
	end

	def destroy
		find_program
		@program.destroy
		respond_to do |format|
			format.html { redirect_to root_url}
			format.js
		end
	end

	def find_program 
		@program = Program.find(params[:id])
	end

end

app/views/programs/_form.html.erb
<%= form_for @program do |f| %> 
	<%= render 'shared/errors', object: @program %> 
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :body %>
		<%= f.text_area :body %>
	</div>
	
	<div class="actions">
		<%= f.submit %>
	</div>


<% end %>

app/views/programs/edit.html.erb
<h1>Edit</h1>
<%= render 'form' %>

app/views/programs/index.html.erb
	<h1>Programs</h1> 
	<div class="column_title pages">
		<%= content_tag :p, link_to("+ New", new_program_path), class: "new_instance_button" if can? :create, Program %>
		<ul>
			<li class="title">Name</li>
		</ul>
		
	</div>

	<ul class="model_table">
		<% @programs.each do |program| %>
			<li>
				<ul class="instance_detail">
					<%= content_tag :li, program.name, class:"name" %>
					
					<%= render "shared/crud_btns", object: program %>
				</ul>
				<br class="clear">
			</li>
		<% end %>
	</ul>

app/views/programs/new.html.erb
<h1>New Page</h1>
<%= render 'form' %>

app/views/programs/show.html.erb
<ul class="model_table">
	<li>
		<ul class="instance_detail">
			<%= content_tag :li, @program.name, class:"name" %><br />
			<%= content_tag :div, raw(@program.body), class: "view_all" %>
			<%= render 'shared/crud_btns', object: @program %>
		</ul>
		<br class="clear">
	</li>
	<br />

	<%= content_tag :li, link_to('View All programs', programs_path) %>
</ul>