config/routes.rb
FlagApp::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :users do 
    collection { post :sort }
    resources :images
    resources :journals
    resources :scrapbooks
  end 

  match 'signup', to: "users#new"
  match 'login', to: "sessions#new"
  match 'logout', to: "sessions#destroy"
  match 'profile', to: "users#show"
  match 'about', to: "static_pages#about"
  match 'dashboard', to: "static_pages#dashboard"
  match 'book', to: "static_pages#book"
  match 'users/:id/scrapbook/day', as:'day', to: "scrapbooks#day"
  match 'users/:id/scrapbook/week', as:'week', to: "scrapbooks#week"
  match 'users/:id/scrapbook/month', as:'month', to: "scrapbooks#month"
  match 'users/:id/scrapbook/year', as:'year', to: "scrapbooks#year"
  match 'weekly_scrapbook', to: "static_pages#weekly"
  match 'monthly_scrapbook', to: "static_pages#monthly"
  match 'yearly_scrapbook', to: "static_pages#yearly"
  match "users/:id/images/:id/resize", to: "images#resize"
  match "users/:id/images/:id/time_frame", to: "images#time_frame"
  match "users/:id/images/:id/z_index", to: "images#z_index"
  match "users/:id/images/:id/drag", to: "images#drag"
  match "users/:id/images/:id/update", to: "images#update"
  match "users/:id/images/:id/edit", to: "images#edit"
  match "users/:id/update", to: "users#update"
  match "users/:id/update_reg_coor", to: "users#update_reg_coor"
  match "users/create", to: "users#create", as: "create_guest"
  match "member_index", to: "users#member_index"
  match "users/:id/regional_coor", to: "users#regional_coor"
  match "static_pages/intro_movie", to: "static_pages#intro_movie", as: "intro_movie"
  
  match "announcement_partial", :to => "announcements#announcement_partial"
  
  match "event_partial", :to => "events#event_partial"
  match "image_partial", :to => "images#image_partial"
  match "coordinators", :to => "users#coordinators"

  resources :users do 
    collection { post :sort }
  	resources :images
    resources :journals
    resources :scrapbooks
  end 
  resources :partials
  resources :messages

  # announcements
  match 'announcements/:id/hide', as: 'hide_announcement', to: 'announcements#hide'
  resources :announcements do
    collection { post :sort }
  end
  match "announcements/:id/announcement_status", to: "announcements#announcement_status", as: "announcement_status"
  match "announcements/:id/announcement_starts_at", to: "announcements#announcement_starts_at", as: "announcement_starts_at"
  match "announcements/:id/announcement_ends_at", to: "announcements#announcement_ends_at", as: "announcement_ends_at"
 
   
  # page
  resources :pages do
    collection { post :sort }
    member { put :link, :status }
  end
  # match 'pages/:id/status', to: 'pages#status', as: 'status'
  
  # announcements
  resources :announcements do 
    resources :statuses_statusables
  end
  
  # events
  resources :events do
    collection { post :sort }
  end
  match 'events/:id/event_status', to: 'events#event_status', as: 'event_status'
  match "events/:id/event_starts_at", to: "events#event_starts_at", as: "event_starts_at"
  match "events/:id/event_ends_at", to: "events#event_ends_at", as: "event_ends_at"

  resources :password_resets
  resources :votes
  resources :links
  resources :sessions
  resources :roles
  resources :programs
  # supermodels
  resources :supermodels do
    collection { post :sort }
  end
  match "supermodels/:id/model_status", :to => "supermodels#model_status", :as => "model_status"
  

  root :to => "pages#show", :id => 'home'

 
end

app/views/shared/_announcements.html.erb
<% Announcement.current(cookies.signed[:hidden_announcement_ids]).each do |announcement| %>
	<%= div_for announcement do %>
		<%= link_to "Hide", hide_announcement_path(announcement), class:"gotit" %>
		<%= announcement.message %>
	<% end %>
<% end %>

app/views/shared/_close.html.erb
<%= content_tag :div, "X", class: "close_form" %>

app/views/shared/_crud_btns.html.erb
<ul class="crud_buttons">
	<% modelK = object.class.name.classify.constantize %>
 	<% klass = object.class.name.downcase %>
	<%= content_tag :li, link_to("edit", "#{klass}s/#{object.id}/edit"), class: "edit" if can? :update, modelK %>
	<%= content_tag :li, link_to("view", "#{klass}s/#{object.id}"), class: "view" if can? :show, modelK %>
	<%= content_tag :li, link_to("delete", "#{klass}s/#{object.id}", :confirm => "are you sure?", :method => :delete ), class: "delete" if can? :delete, modelK %>
</ul>

app/views/shared/_crud_btns_without_view.html.erb
<ul class="crud_buttons">
	<% modelK = object.class.name.classify.constantize %>
 	<% klass = object.class.name.downcase %>
	<%= content_tag :li, link_to("edit", "#{klass}s/#{object.id}/edit"), class: "edit" if can? :update, modelK %>
	<%= content_tag :li, link_to("delete", "#{klass}s/#{object.id}", :confirm => "are you sure?", :method => :delete ), class: "delete" if can? :delete, modelK %>
</ul>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		
		<h2><%= pluralize(object.errors.count, "error") %>
			prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
			from being saved:</h2>
		<p>There were problems with the following fields:</p>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		
	</div>
<% end %>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="header_container">  
 	<div class="thousand_wide_container ">
    <div class="flag_header_logo">
        <a href="/">
          <%= image_tag "logo.png", class:"right students" %>
        </a>   
    </div>
      <!-- Start of the nav bar content -->   
            <ul class="left nav_bar">
             <!--  <%= content_tag :li, link_to("Home", root_path) %>
              <%= content_tag :li, link_to("About", about_path) %> -->
              <% @pages = Page.published.order_by_position %>
              <% top_link = Link.find_by_location("top_link").id %>
              <% @pages.each do |page| %>
                <% if page.link_ids.include?(top_link) %>
                     <%= content_tag :li, link_to(page.title, [page]) %>
                <% end %>
              <% end %>

            </ul>

          <ul class="left nav_bar">
            <%= content_tag :li, link_to("Community", member_index_path) if registered_member%>
            <% if registered_member %> 

                <%= content_tag :li, link_to("My Scrapbook", root_path+"users/"+current_user.id.to_s+"/scrapbook/day") %>

            <% else %>
                <%= content_tag :li, link_to("Scrapbook", book_path) if current_user %>

            <% end %>
          </ul>
          <!-- The drop down menu --> 
          <!--        <ul class="left_side nav_bar">
          
              <%= content_tag :li, "Guest pass", class: "guest_btns guest_pass" if current_user && current_user.guest? %>

              <%= content_tag :li, link_to(current_user.last_name, user_path(current_user.id)) if current_user %>
              
          </ul> -->

          <ul class="right nav_bar">
              <%= content_tag :li, link_to( image_tag("movie.png", :size => "35x30", class:"right"), intro_movie_path, remote: true), class: "movie" %>
              <%= content_tag :li, link_to(current_user.first_name, user_path(current_user.id)) if current_user && current_user.guest == false %>
              <% if current_user %>
                  <% if current_user.guest? %>
                    <%= content_tag :li, link_to("Register as new user", new_user_path) %>
                    <%= content_tag :li, link_to("Sign In", new_session_path, remote: true) %>
                  <% else %>
                    <%= content_tag :li, link_to("Dashboard", dashboard_path) if current_user.role? :Admin %>
                    <%= content_tag :li, link_to("Sign Out", logout_path, method: "delete") %>
                  <% end %>
              <% else %>
                  <%= content_tag :li, link_to("Sign In", new_session_path, remote: true), class: 'drop-auth' %>
                  <%= content_tag :li, link_to("Sign Up", new_user_path) %>  
              <% end %>
              <div class="login_form_container"></div>
          </ul>
    </div>
</div>
    

app/views/shared/_scrap_template.html.erb
<%= @beg_range %> to <%= @end_range %><br />
bread_crumb:<%= @bread_crumb = @beg_range%>
<%= render('javascript/image') %>

<!-- Go To Week link button with a bread crumb -->

<% image_num = 0 %>
<%= render('scrapbooks/shared/'+page+'_images') %>

<%= render('scrapbooks/shared/up_down_prev_next_links') %>

<%= render('shared/journal_script') %>
<div class="time_navigation">
	<%= image_tag "delete.png", class: "delete_time_nav", size: "15x15" %>
	<ul class="thumbnail_images">
		<% if @month_images %>
			<% @month_images.each do |image| %>
			<div class="thumbnail_container">
				<li class="thumb_drag" data-id="<%= image.id %>" data-src="<%= image.image_url(:scrap) %>" data-range="day" ><%= link_to image_tag(image.image_url(:scrap), width: "25px", height: "25px")  %></li>
			</div>
			<% end %>
		<% end %>
	</ul>
	<%= render('menus/by_day') %>
	<%= render('menus/by_week', :beg_month => @first_of_month ) %>
	<%= render('menus/by_month', :beg_range => @first_of_month ) %>
</div>

app/views/shared/_sidebar.html.erb
 
<div class="sidebar">
	<div class="sidbar_tables find-co">
		<a href="coordinators/">
			<%= image_tag "find-coordinator.png", class: "find-coordinator" %>
		</a>
	</div>	
	<div class="sidbar_tables">
		<h2>Latest News</h2>
		<% @announcements.each do |a| %>
			<div class="item">
				<ul class="table_row">
					<%= content_tag :li, a.title, class: "title"  %>
					<%= content_tag :li, raw(a.message), class: "message" %>
					
				</ul>
				<br class="clear">
			</div>
		<% end %>
		<br class="clear">
	</div>
	<div class="sidbar_tables">
		<h2>Upcoming Events</h2>
		<% @events.each do |e| %>
			<div class="item">
				<ul class="table_row">
					<%= content_tag :li, e.title, class: "title" %>
					<%= content_tag :li, raw(e.body), class: "message" %>
					
				</ul>
				<br class="clear">
			</div>
		<% end %>
		<br class="clear">
	</div>

</div>

app/views/shared/_sign_in_form.html.erb
<!--SIGNIN Ajax -->
<div class="auth-form home_forms">
    <%= render("shared/close") %>
    <%= form_tag sessions_path do %>
       <%= render 'sessions/authentication' %>
    <% end %>
</div> 

app/views/shared/_sign_up_form.html.erb
<!--SIGNUP  AJAX-->
<div class="sign-up-form home_forms">  
	<%= render 'form' %>
	<% end %>
</div>

app/views/shared/_status_form_field.html.erb
<div class="field statuses">
  	<%= f.label :statuses %><br />
    <% @statuses.each do |status| %>
    	<div id="<%= status.current_state %>_status">
	      <%= check_box_tag "#{model_name}[status_ids][]", status.id, @statusable.statuses.include?(status) %>  
	      <%= status.current_state %>
	    </div>  
    <% end %>
</div>

app/views/shared/quick_partial_view.html.erb
<%= content_tag :h2, "#{@model_name} Partial", class: "partial_title" %>
<%= content_tag :h3, "If you would like this partial to show up on a specific page, click on that page link below and check '#{@model_name}' under 'Partials to be displayed'", class: "partial_description" %>
<%= content_tag :h3, "Page Links", class: "partial_description" %>
<% Page.all.each do |page| %>
	<%= content_tag :div, link_to( "#{page.title} page", "pages/#{page.slug}/edit"), class: "partial_link" %>
<% end %>

<br class="clear" />
<%= render "#{@model_name.downcase}s/#{@model_name.downcase}_partial" %>